name: Build, push to ECR, deploy App Runner (hfg-user-onboard)

on:
  push:
    branches: [ "main" ]
    # Remove paths filter if this repo contains only this service
    paths:
      - ".github/workflows/deploy-user-onboard.yml"
      - "**/*"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  AWS_ACCOUNT_ID: ${{ vars.ACCOUNT_ID }}              # or: ${{ secrets.ACCOUNT_ID }}
  ECR_REPOSITORY: hfg-user-onboard
  APP_RUNNER_SERVICE: hfg-user-onboard
  CPU: "0.5 vCPU"
  MEMORY: "1 GB"
  IMAGE_PORT: "5052"

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GitHubActions-AppRunner
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Ensure ECR repository exists
        run: |
          set -e
          aws ecr describe-repositories \
            --repository-names "${{ env.ECR_REPOSITORY }}" \
            --region "${{ env.AWS_REGION }}" >/dev/null 2>&1 || \
          aws ecr create-repository \
            --repository-name "${{ env.ECR_REPOSITORY }}" \
            --image-scanning-configuration scanOnPush=true \
            --region "${{ env.AWS_REGION }}"
        # Requires the role to have ecr:CreateRepository permission

      - name: Build and push image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.ECR_REPOSITORY }}
          TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$TAG .
          docker push $REGISTRY/$REPOSITORY:$TAG
          docker tag  $REGISTRY/$REPOSITORY:$TAG $REGISTRY/$REPOSITORY:latest
          docker push $REGISTRY/$REPOSITORY:latest

      - name: Deploy to App Runner
        uses: awslabs/amazon-app-runner-deploy@main
        with:
          service: ${{ env.APP_RUNNER_SERVICE }}
          image: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          access-role-arn: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/AppRunnerECRAccessRole
          cpu: ${{ env.CPU }}
          memory: ${{ env.MEMORY }}
          port: ${{ env.IMAGE_PORT }}
          region: ${{ env.AWS_REGION }}
          min-size: 1
          max-size: 2
          healthcheck-path: /
